// Lista de palavras de 5 letras em inglês para o Wordle
export const WORD_LIST = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
  "agent", "agree", "ahead", "alarm", "album", "alert", "align", "alike", "alive", "allow",
  "alone", "along", "alter", "amber", "amend", "angel", "anger", "angle", "angry", "apart",
  "apple", "apply", "arena", "argue", "arise", "armor", "array", "arrow", "aside", "asset",
  "audio", "avoid", "awake", "award", "aware", "badly", "baker", "bases", "basic", "basis",
  "beach", "began", "begin", "begun", "being", "below", "bench", "billy", "birth", "black",
  "blame", "blank", "blind", "block", "blood", "bloom", "board", "boost", "booth", "bound",
  "brain", "brand", "brass", "brave", "bread", "break", "breed", "brief", "bring", "broad",
  "broke", "brown", "build", "built", "buyer", "cable", "calif", "carry", "catch", "cause",
  "chain", "chair", "chaos", "charm", "chart", "chase", "cheap", "check", "chest", "chief",
  "child", "china", "chose", "civil", "claim", "class", "clean", "clear", "click", "cliff",
  "climb", "clock", "close", "cloth", "cloud", "coach", "coast", "could", "count", "court",
  "cover", "crack", "craft", "crash", "crazy", "cream", "crime", "cross", "crowd", "crown",
  "crude", "curve", "cycle", "daily", "dance", "dated", "dealt", "death", "debut", "delay",
  "delta", "dense", "depth", "doing", "doubt", "dozen", "draft", "drama", "drank", "drawn",
  "dream", "dress", "drill", "drink", "drive", "drove", "dying", "eager", "early", "earth",
  "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "event",
  "every", "exact", "exist", "extra", "faith", "false", "fault", "fiber", "field", "fifth",
  "fifty", "fight", "final", "first", "fixed", "flash", "fleet", "floor", "fluid", "focus",
  "force", "forth", "forty", "forum", "found", "frame", "frank", "fraud", "fresh", "front",
  "fruit", "fully", "funny", "giant", "given", "glass", "globe", "going", "grace", "grade",
  "grand", "grant", "grass", "grave", "great", "green", "gross", "group", "grown", "guard",
  "guess", "guest", "guide", "happy", "harry", "heart", "heavy", "hence", "henry", "horse",
  "hotel", "house", "human", "ideal", "image", "imply", "index", "inner", "input", "issue",
  "japan", "jimmy", "joint", "jones", "judge", "known", "label", "large", "laser", "later",
  "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon", "level", "lewis",
  "light", "limit", "links", "lives", "local", "logic", "loose", "lower", "lucky", "lunch",
  "lying", "magic", "major", "maker", "march", "maria", "match", "maybe", "mayor", "meant",
  "media", "metal", "might", "minor", "minus", "mixed", "model", "money", "month", "moral",
  "motor", "mount", "mouse", "mouth", "movie", "music", "needs", "never", "newly", "night",
  "noise", "north", "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "order",
  "other", "ought", "paint", "panel", "paper", "party", "peace", "peter", "phase", "phone",
  "photo", "piece", "pilot", "pitch", "place", "plain", "plane", "plant", "plate", "point",
  "pound", "power", "press", "price", "pride", "prime", "print", "prior", "prize", "proof",
  "proud", "prove", "queen", "quick", "quiet", "quite", "radio", "raise", "range", "rapid",
  "ratio", "reach", "ready", "refer", "relax", "reply", "right", "rival", "river", "robin",
  "roger", "roman", "rough", "round", "route", "royal", "rural", "scale", "scene", "scope",
  "score", "sense", "serve", "seven", "shall", "shape", "share", "sharp", "sheet", "shelf",
  "shell", "shift", "shine", "shirt", "shock", "shoot", "short", "shown", "sight", "since",
  "sixth", "sixty", "sized", "skill", "sleep", "slide", "small", "smart", "smile", "smith",
  "smoke", "solid", "solve", "sorry", "sound", "south", "space", "spare", "speak", "speed",
  "spend", "spent", "split", "spoke", "sport", "staff", "stage", "stake", "stand", "start",
  "state", "steam", "steel", "stick", "still", "stock", "stone", "stood", "store", "storm",
  "story", "strip", "stuck", "study", "stuff", "style", "sugar", "suite", "super", "sweet",
  "table", "taken", "taste", "taxes", "teach", "terry", "texas", "thank", "theft", "their",
  "theme", "there", "these", "thick", "thing", "think", "third", "those", "three", "threw",
  "throw", "tight", "times", "title", "today", "topic", "total", "touch", "tough", "tower",
  "track", "trade", "trail", "train", "treat", "trend", "trial", "tribe", "trick", "tried",
  "tries", "troop", "truck", "truly", "trump", "trust", "truth", "twice", "under", "undue",
  "union", "unity", "until", "upper", "upset", "urban", "usage", "usual", "valid", "value",
  "video", "virus", "visit", "vital", "vocal", "voice", "waste", "watch", "water", "wheel",
  "where", "which", "while", "white", "whole", "whose", "woman", "women", "world", "worry",
  "worse", "worst", "worth", "would", "wound", "write", "wrong", "wrote", "yield", "young",
  "youth", "house", "world", "horse", "bread", "music", "smile", "peace", "river", "ocean",
  "plant", "storm", "clock", "heart", "light", "night", "beach", "stone", "blood", "bones",
  "brain", "chair", "chess", "crown", "diary", "drums", "Earth", "flame", "glass", "globe",
  "grace", "grave", "honor", "ivory", "kings", "knife", "lemon", "lotus", "maple", "melon",
  "metal", "night", "olive", "orbit", "paint", "pearl", "piano", "prism", "quake", "quill",
  "quest", "quiet", "reign", "rhyme", "roast", "royal", "ruins", "saint", "seeds", "shade",
  "shark", "sheep", "shell", "shirt", "shore", "sight", "skies", "skull", "slate", "sleep",
  "slope", "smoke", "snail", "snake", "snare", "sound", "spark", "spell", "spoke", "sport",
  "spray", "squad", "staff", "stage", "stamp", "stand", "stars", "start", "state", "steps",
  "stick", "sting", "stock", "storm", "strap", "straw", "strip", "study", "swing", "sword",
  "table", "taste", "thorn", "thumb", "timer", "titan", "toast", "tower", "track", "train",
  "trash", "treat", "trial", "tribe", "trick", "trout", "truce", "trunk", "trust", "truth",
  "tulip", "twist", "unity", "valve", "vault", "verse", "vigil", "viral", "vital", "vouch",
  "wagon", "wager", "waste", "water", "wheat", "whiff", "whirl", "witch", "woman", "woods",
  "worth", "wrath", "wreck", "write", "yacht", "yanks", "years", "yeast", "yield", "youth"
];

// Função para pegar uma palavra aleatória
export function getRandomWord(): string {
  return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)].toUpperCase();
}
